### PR TITLE
honor nosetarch all the way

### PR DESCRIPTION
**Pull request by holymonson**
Fix `nosetarch` support which is honored by `arch-nspawn` and `mkarchroot` but not `archbuild` or `makechrootpkg`.

### CODE REVIEW

**Comment by anthraxx** [comment]
why shouldn't the architecture being set? The general workflow would be to have an appropriate wrapped that respects the correct CARCH you want to have via a makepkg.conf and distribute it as makepkg-${repo}-${arch}.conf". This can then be used from an appropriate wrapper like extra-arm64-build

**Comment by holymonson** [comment]
setarch on x86_64 couldn't recognise ARM architecture, and that why nosetarch was introduced at https://github.com/archlinux/devtools/commit/5b9c06d275dd1a2dca09514e39f853bd9c57be3a .

**Comment by anthraxx** [comment]
That makes sense for dedicated chroots, but if you are using them through the `archbuild` chain anyway, you have your own wrapper. Won't it work equally by just having an appropriate makepkg-${repo}-${arch}.conf that has an empty CARCH? That doesn't require to forcefully always pass `-s` to make things work. This may need tiny adjustments in `archbuild.in` exclusively.
PS: Please also change the completion files when adjusting options.

**Comment by holymonson** [comment]
We can't empty `CARCH` in makepkg-${repo}-${arch}.conf because libmakepkg and some PKGBUILDs will use it. But you do enlighten me that we could check `CARCH` first. Please see #43.

**Comment by anthraxx** [comment]
I would prefere #43 as that doesn't require special calls to a archbuild symlink target but just a clean invocation. If you believe that solves the requirements for arm builds, please close this issue

**Comment by klausenbusk** [comment]
devtools has been migrated to our GitLab, closing..

Migrated to: https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/41

**Pull request closed without merging**
