### PR TITLE
respect SRCEXT from makepkg.conf

### PR DESCRIPTION
**Pull request by kgizdov**
as the title says

### CODE REVIEW

**Comment by anthraxx** [comment]
this patch does not work as you expect, if you dont expotr `$SRCEXT` in the invoking shell this variable will simply be empty and the glob will just cat whatever is in that directory.

**Comment by kgizdov** [comment]
@anthraxx on the contrary, the variable is available because of `makepkg --source` call. Not to mention, if you were right, the whole script wouldn't work. I tested it myself.

**Comment by Foxboron** [comment]
@kgizdov Why would `makepkg --source` make `$SRCEXT` available?

**Comment by kgizdov** [comment]
@anthraxx it makes everything in `makepkg.conf` available. Look at PKGDEST being used directly too. Have you tried running the script or? Does it work for you?

**Comment by Foxboron** [comment]
@kgizdov `$PKGDEST` is available because of the `load_makepkg_config` function on line 125.
https://github.com/archlinux/devtools/blob/03c6b2a892d6b45fe4b2571caa56b7c96f2f68e5/offload-build.in#L125

**Comment by kgizdov** [comment]
@anthraxx Indeed, last discussion I saw on this was about having makepkg source its environment. Nevermind, I will update the PR

**Comment by anthraxx** [comment]
what? this is a child process invocation of makepkg and not a function call, it can't source anything magically into the parent process. I am 100% right and it would be great to technically verify what I have explained before claiming I didn't do my homework.

**Comment by kgizdov** [comment]
@anthraxx yes, you are correct, I misunderstood where/how this is done, based on old discussion.

Also, mentioned the wrong person because being on my phone - meant to answer @Foxboron in a couple of those.

Is it ok now?

**Comment by kgizdov** [comment]
is anything else needed to be done about this?

**Comment by anthraxx** [comment]
applied in 4915c4e2a41fba81ec303a8b8b14e1577606fdd3
thanks for the patch

**Pull request closed without merging**
